name: Update Translation Source

on:
  workflow_dispatch:
  schedule:
    # runs at the start of each month (UTC)
    - cron: '0 0 1 * *'

jobs:
  translations:
    # Do not run the scheduled workflow on forks
    if: (github.event != 'schedule' || github.repository_owner == 'Cockatrice')

    name: Update translation source strings
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install lupdate
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qttools5-dev-tools

      - name: Update Cockatrice translation source
        id: cockatrice
        shell: bash
        env:
          FILE: 'cockatrice/translations/cockatrice_en@source.ts'
          DIRS: 'cockatrice/src common'
        run: .ci/update_translations.sh

      - name: Update Oracle translation source
        id: oracle
        shell: bash
        env:
          FILE: 'oracle/translations/oracle_en@source.ts'
          DIRS: 'oracle/src'
        run: .ci/update_translations.sh

      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.2
        with:
          template: .ci/update_translations_template.md
          vars: |
            cockatrice_output: ${{ steps.cockatrice.outputs.output }}
            oracle_output: ${{ steps.oracle.outputs.output }}
            commit: ${{ github.sha }}

      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: |
            cockatrice/translations/cockatrice_en@source.ts
            oracle/translations/oracle_en@source.ts
          commit-message: Update translation source strings
          # author is the owner of the commit
          author: github-actions <github-actions@github.com>
          branch: ci-update-translations
          delete-branch: true
          title: '[Translations] Update source strings'
          body: ${{ steps.template.outputs.result }}
          labels: |
            CI
            Translation
          draft: false

      - name: PR Status
        shell: bash
        env:
          STATUS: ${{ steps.create_pr.outputs.pull-request-operation }}
        run: |
          if [[ "$STATUS" == "" ]]; then
            echo "PR unchanged:"
          else
            echo "PR $STATUS:"
          fi
          echo "ticket #${{ steps.create_pr.outputs.pull-request-number }}"
          echo "url ${{ steps.create_pr.outputs.pull-request-url }}"
