name: Build Web

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/web-*.yml'
      - 'webclient/**'
      - '!**.md'
  pull_request:
    paths:
      - '.github/workflows/web-*.yml'
      - 'webclient/**'
      - '!**.md'

jobs:
  build-web:
    name: React (Node ${{matrix.node_version}})

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: webclient

    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 16
          - lts/*

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        id: setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node_version}}
          cache: 'npm'
          cache-dependency-path: 'webclient/package-lock.json'

      - name: Install dependencies
        run: npm clean-install

      - name: Build app
        run: npm run build

      - name: Test app
        run: npm run test
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{steps.setup.outputs.node-version}}-build
          path: webclient/build
          if-no-files-found: error
